title: GATE ComputerScience
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  questions:
    output: true
    name: "Questions"
  exams:
    output: true
    name: "GATE Exams"
  learn:
    output: true
    name: "Learn"
    sort_by: serial

# Frontmatter
defaults:
  - scope:
      path: ""
      type: "questions"
    values:
      layout: "question"
      set: 1
      marks: 1
      section: technical
      type: mcq
  - scope:
      path: ""
      type: "exams"
    values:
      layout: "exam"
  - scope:
      path: ""
      type: "learn"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author:
        name: Sumeet Mathpati
        email: sumeet.mathpati@gmail.com
        avatar: sumeet.jpg
        bio: "Back-end developer, CS graduate, love FOSS. Uses Python, Go, C."
