for i in range(1, 66):
    f = open(f"./{i}.md", "w")
    f.write("---\n")
    f.write(f"qno: {i}\n")
    f.write(f"year: 2019\n")
    f.write(f"set: 1\n")
    f.write(f"type: mcq\n")
    f.write(f"option_a:\n")
    f.write(f"option_b:\n")
    f.write(f"option_c:\n")
    f.write(f"option_d:\n")
    f.write(f"correct_option:\n")
    f.write(f"nav_answer:\n")
    f.write("---")
    f.close()
